### ISSUE TITLE
ImportError: can't perform relative import

### ISSUE THREAD

**Issue by mr-pepe69** [flrrth/pico-htu21d#3]
i tried copping the 2 files (htu21d.py and htu21d_configuration) into the raspberry pi and i ran the example code and it doesnt work and tells me:
`Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "htu21d.py", line 6, in <module>
ImportError: can't perform relative import`
i tried renaming this line
`from .htu21d_configuration import HTU21DConfiguration`
into
`from htu21d_configuration import HTU21DConfiguration`
and showed me this other error that i also don't understand
`Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "htu21d.py", line 24, in __init__
  File "htu21d.py", line 29, in reset
OSError: [Errno 5] EIO`
edit: i ended up coping the whole folder to the pi and that solved the first problem, the second problem i still can't solve it.

**Comment by mr-pepe69** [comment]
i solved it, it was 100% my fault. i didnt connect the pins right or i soldered improperly, i'm not sure where i failed, but i fixed it, quick advice for anyone that had the same problem. add this after this line(i added the freq=40000 but is not neccesary) `i2c0 = I2C(0, sda=i2c0_sda, scl=i2c0_scl,freq=40000)`
this line will help you troubleshoot any ic2 device and remember to check if you protoboard cables work, use a multimeter and pre check if your cables work before plugging anything, it will save you hours and you are not going to make you look a bit dumb like me.
`devices = i2c0.scan()
if len(devices) == 0:
  print("I2C Address      : No I2C devices found")
else:
  print("I2C Address      : "+hex(devices[0]))`
